[colors]
background = 00282828
bg-module = #282828
background-alt = #3c3836
foreground = #fbf1c7
primary = #B8BB26
secondary = #83A598
alert = #fb4934
disabled = #6272a4
Purple = #d3869b
Green = #689d69
Cyan = #8ec07c
Pink = #fabd2f
Blue = #83a598
orange = #fe8019
Red = #fb4934

[bar/main]
width = 100%
height = 20pt
radius = 12 
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 3pt
border-color = #00000000
padding-left = 0
padding-right = 0
module-margin = 0
separator = ""
separator-foreground = ${colors.disabled}
font-0 = "JetBrainsMono Nerd Font:style=Bold:size=10;3"
font-1 = "JetBrainsMono Nerd Font:size=14;4"
font-2 = "JetBrainsMono Nerd Font:size=10;3"
font-3 = "JetBrainsMono Nerd Font:size=10;3"
font-4 = "JetBrainsMono Nerd Font:size=14;4"

; Bar layout
modules-left = menu p-dir2 esp i3
modules-center = p-esq date p-dir esp p-esq memory cpu p-dir
modules-right = p-esq tray p-dir esp p-esq pulseaudio p-dir esp p-esq powermenu


enable-ipc = true

[module/tray]
type = internal/tray
format-background = ${colors.bg-module}
format-margin = 0pt
tray-background = ${colors.bg-module}
tray-spacing = 10pt

[module/i3]
type = internal/i3

; Focused workspace
label-focused = %index%
label-focused-foreground = ${colors.Purple}
label-focused-padding = 1

; Unfocused workspace
label-unfocused = %index%
label-unfocused-foreground = ${colors.foreground}
label-unfocused-padding = 1

; Visible workspace (on another monitor, if any)
label-visible = %index%
label-visible-foreground = ${colors.Purple}
label-visible-padding = 1

; Urgent workspace
label-urgent = %index%
label-urgent-foreground = ${colors.alert}
label-urgent-padding = 1

; Separator
label-separator = |
label-separator-foreground = ${colors.disabled}

[module/xwindow]
type = internal/xwindow
label = %title:0:10:...%

[module/memory]
type = internal/memory
interval = 20
format-background = ${colors.bg-module}
format-prefix = " "
format-prefix-foreground = ${colors.Blue}
label = %{F#d8dee9}%percentage_used%%
label-padding-left = 1
label-padding-right = 3

[module/cpu]
type = internal/cpu
interval = 2
format-background = ${colors.bg-module}
format-prefix = " "
format-prefix-foreground = ${colors.Purple}
label = %{A1:gnome-terminal -e btop:}%{F#d8dee9}%percentage:2%%%{F-}%{A}
label-padding-left = 1
label-padding-right = 1

[module/pulseaudio]
type = internal/pulseaudio
format-volume-background = ${colors.bg-module}
format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.orange}
format-volume = <label-volume>
label-volume = %{F#d8dee9}%percentage%%
label-muted = "    "
format-muted-background = ${colors.bg-module}
label-muted-foreground = ${colors.disabled}
label-padding-left = 1
label-padding-right = 3
sink = alsa_output.usb-SADES_Electronics_Inc._SADES_Locust_Plus-00.iec958-stereo

[module/powermenu]
type = custom/script
format-background = ${colors.bg-module}
label-padding-left = 1
label-padding-right = 1
exec = echo "%{F#fbf1c7} ⏻ %{F-}%{F#bd93f9}  %{F-}"
click-left = ~/.config/rofi/off-pc/powermenu.sh

[module/menu]
type = custom/script
format-background = ${colors.Cyan}
exec = echo "%{F#6272a4}  %{F-}%{F#16171d} "
click-left = ~/.config/rofi/app-managers/launch.sh

[module/date]
type = internal/date
interval = 1
format-background = ${colors.bg-module}
date =  %a, %d-%b  |  %R
label = %{A1:gnome-calendar:}%date%%{A}
label-padding-left = 1
label-padding-right = 0

[module/p-esq]
type = custom/text
content = ""
content-foreground = ${colors.bg-module}
content-font = 2

[module/p-dir]
type = custom/text
content = ""
content-foreground = ${colors.bg-module}
content-font = 2

[module/p-dir2]
type = custom/text
content = ""
content-foreground = ${colors.Cyan}
content-font = 2

[module/esp]
type = custom/text
content = "  "
content-foreground = ${colors.bg-module}
content-font = 2
